### ISSUE TITLE
Research and finalize some final points w/ Yearn

### ISSUE THREAD

**Issue by yuval-weiss** [tempus-finance/tempus-protocol#389]
1. Check what needs to be done for Yearn partnership program
2. should we increase the default `maxLoss`?
3. Is there a way to update Yearn's interest rate? `TempusPool.updateInterestRate`

**Comment by axic** [comment]
1. Partnership: https://docs.yearn.finance/partners/introduction

2. Opened #487.

3. The [report function](https://github.com/yearn/yearn-vaults/blob/main/contracts/Vault.vy#L1692) seems to be the one which updates `self.lastReport`/`self.lockedProfit`/etc. which are the stored parts. This function can only be called by authorized users.

**Comment by axic** [comment]
@yuval-weiss I suggest we close this issue as only keep #487.
