### ISSUE TITLE
[amm] Implement swap fees in AMM

### ISSUE THREAD

**Issue by mijovic** [tempus-finance/tempus-protocol#578]
Also decide if we want fixed or variable swap fees, or combination...
I guess we can implement strategy and then deploy different ones with each pool

**Comment by mijovic** [comment]
I have had ideas on initial strategies:
1. Simple fixed swap fee which ideally is set as immutable
2. Variable swap fee, set from outside by calling a method
3. Decreasing swap fee over time, starting at x% at deployment and decreasing over to y% on maturity

My original idea was to have:
```
uint256 internal immutable swapFeeStragetgy;
bytes private swapFeeData;
```
If `swapFeeStrategy` is less than or equal to `SWAP_FEE_MAX`, it acts as a percentage, otherwise, it acts as a strategy that can be either a predefined number of strategies.

All the data needed for that strategy can be stored in `bytes` array, and that can be only one percentage value in case of strategy 2 and two percentage values in the case of strategy 3.

I would allow setting `swapFeeData` from outside (it is questionable for which strategies we want to allow this and how - for 2 it is easy, while for 3 it can be tricky).

**Comment by RedFox20** [comment]
Motivational PR: https://github.com/tempus-finance/tempus-protocol/pull/582/files
